### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by grylem** [wiedi/unhardlink#2]
Hi
There is no file config.h.in for configure script.
Thanks.
P.S.
maybe you can add also hardlinks to symlinks?

**Comment by wiedi** [comment]
Hi, thanks for reporting this.

The file can be generated via `autoreconf`. I've also added a pre-generated version to the repo now, so running `./configure && make` should be enough.

I'm not sure I understand the question about symlinks.

**Comment by grylem** [comment]
> I'm not sure I understand the question about symlinks.

The possibility of conversion hardlinks to symlinks.

**Comment by wiedi** [comment]
I'm not sure that would be easily possible. You would already have to know which files link to the same inode and you would have to specify which ones should be the source and which the target.
I suspect that would be very inefficient to implement and inconvenient to use. At that point the user would already need all the  details and could just do `rm b && ln -s a b`.

**Comment by grylem** [comment]
Thanks for the explanation.
